sudo: required
before_install:
    - openssl aes-256-cbc -K $encrypted_063cb9d28ed8_key -iv $encrypted_063cb9d28ed8_iv -in deploy/deploy.tar.enc -out deploy/deploy.tar -d
    - tar -C deploy -xf deploy/deploy.tar 
    - rm deploy/deploy.tar 
install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq realpath 
    - bundle install
jdk:
    - oraclejdk8
rvm:
    - rbx 
script: 
    - make clean dist 
    - bash deploy/deploy.sh 
